# Generated by Django 3.2.12 on 2024-04-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
